# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aliop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur', models.IntegerField()),
                ('username', models.CharField(max_length=64)),
                ('method', models.CharField(max_length=64)),
                ('url', models.CharField(max_length=128)),
            ],
        ),
    ]
